task_manage/routes.py
import os
import shutil
import sqlalchemy.exc

from task.utils import register_user_avatar, send_reset_email
from task_manage.forms import LoginForm, RegistrationForm, UpdateAccountForm, ResetRequestForm, ResetPasswordForm
from task_manage import bcrypt, database
from models import check_password_hash, User, Task

from flask import render_template, request, redirect, flash, url_for, Blueprint, abort
from flask_login import current_user, login_user, logout_user, login_required

from sqlalchemy import or_
from datetime import datetime

main = Blueprint('main', __name__)


@main.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data,
                    password=hashed_password)

        database.session.add(user)
        database.session.commit()
        if user.id == 1:
            user.is_admin = True
            database.session.commit()
        full_path = os.path.join(os.getcwd(), f'task_manage/static/users/{user.username}/avatars')
        if not os.path.exists(full_path):
            os.makedirs(full_path)
        shutil.copy(f'{os.getcwd()}/task_manage/static/users/default.jpg', full_path)
        flash('Account successfully created. You can redirect to log into your account.')
        return redirect(url_for('main.login'))
    return render_template('register.html', form=form, title='Registration', legend='Registration')


@main.route('/')
def index():
    users = User.query.all()
    return render_template('index.html', users=users)


@main.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit:
        user = User.query.filter(or_(User.username == form.username.data, User.email == form.email.data)).first()
        if user and check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.account'))
        else:
            if form.username.data or form.email.data or form.password.data:
                flash('Failed auth. Check your login or password', 'danger')
    return render_template('login.html', form=form, title='Login', legend='Enter')


@main.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    user = User.query.filter_by(username=current_user.username).first()
    users = User.query.all()
    tasks = Task.query.all()

    if request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    if form.validate_on_submit():
        old_path = os.path.join(os.getcwd(), f'task_manage/static/users/{user.username}/avatars')
        new_path = os.path.join(os.getcwd(), f'task_manage/static/users/{form.username.data}/avatars')
        if os.path.exists(old_path):
            os.rename(old_path, new_path)
        current_user.username = form.username.data
        current_user.email = form.email.data

        if form.avatar.data:
            current_user.img_file = register_user_avatar(form.avatar.data)

        database.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('main.account'))

    image_file = url_for('static', filename=f'users/{current_user.username}/avatars/{current_user.img_file}')
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form,
                           users=users, tasks=tasks)

@main.route('/user_delete/<string:username>', methods=['GET', 'POST'])
@login_required
def delete_user(username):
    try:
        user = User.query.filter_by(username=username).first_or_404()
        if user and user.id != 1:
            database.session.delete(user)
            database.session.commit()
            full_path = os.path.join(os.getcwd(), 'task_manage', 'static', 'users', user.username)
            shutil.rmtree(full_path)
            flash(f'User {username} has been removed.', 'info')
            return redirect(url_for('main.account'))
        else:
            flash("You cannot delete admin's account.", 'info')
            return redirect(url_for('main.account'))


    except sqlalchemy.exc.IntegrityError:

        flash(f'User {username} has  unfinished tasks.', 'warning')
        return redirect(url_for('main.account'))

    except FileNotFoundError:
        return redirect(url_for('main.account'))


@main.route('/logout')
def logout():
    current_user.last_seen = datetime.now()
    database.session.commit()
    logout_user()
    return redirect(url_for('main.index'))


@main.route('/')
def home_page():

    return render_template('main.index')


@main.route('/assign_admin/<int:user_id>', methods=['GET', 'POST'])
@login_required
def assign_admin(user_id):
    if current_user.is_admin:
        user = User.query.get(user_id)
        if user:
            if request.method == 'POST':
                user.is_admin = True
                database.session.commit()
                flash('User assigned as admin.', 'success')
                return redirect(url_for('main.index'))
            else:
                return render_template('assign_admin.html', user=user)
        else:
            abort(404)
    else:
        abort(403)

@main.route('/admin', methods=['GET', 'POST'])
@login_required
def admin():
    if current_user.is_admin:
        users = User.query.all()
        return render_template('admin.html', users=users, title='Admin')
    else:
        abort(403)


@main.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = ResetRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('Check your email for details.', 'info')
        return redirect(url_for('main.login'))

    return render_template('reset_request.html', form=form, title='Resetting Request ')

@main.route('/reset_password/<token>', methods=['GET', 'POST'])
def token_reset(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Invalid token.', 'warning')
        return redirect(url_for('main.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_pass = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_pass
        database.session.commit()
        flash('Your password has been updated, you can login.', 'success')
        return redirect(url_for('main.login'))
    return render_template('reset_token.html', form=form, title='Password reset')

task_manage/templates/account.html
{% extends 'base.html' %}

{% block menu %}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/account.css') }}">
    <header class="header">
        <div class="logo">
            <img src="{{ url_for('static', filename='img/logo.png') }}" alt="logo">
        </div>
        {% if current_user.is_authenticated %}
            <div class="avatar">
                <img id="avatar-img" src="{{ image_file }}"
                     alt="{{url_for('static', filename='users/default.jpg')}}">
            </div>
        {% endif %}
        <ul class="Main_menu">
            <li><a href="{{ url_for('main.index') }}"><p>Main page</p></a></li>
            {% if current_user.is_authenticated %}
                <li><a href="/tasks"><p>Tasks</p></a></li>
                <li><a href="/account"><p>Account</p></a></li>
                <li><a href="/tasks/create"><p>Add task</p></a></li>
                <li><a href="{{ url_for('main.logout') }}"><p>Logout</p></a></li>
                <li><a href="{{ url_for('main.index') }}"><p>Home</p></a></li>
            {% else %}
                <li><a href="{{ url_for('main.login') }}"><p>Login</p></a></li>
                <li><a href="{{ url_for('main.register') }}"><p>Register</p></a></li>
            {% endif %}
            {% if current_user.is_authenticated and current_user.is_admin %}
                <li><a href="/admin"><p>admin</p></a></li>
            {% endif %}
        </ul>
    </header>
{% endblock menu %}

{% block content %}
    <div class="payday2-style">
        {% if current_user.is_authenticated %}
            <h1>Hello, {{ current_user.username }}</h1>
            {%if current_user.last_seen%}
            <h2>Last seen: {{ current_user.last_seen.strftime('%Y-%m-%d %H:%M') }}</h2>
            {% endif %}
            <p>Your email is: {{ current_user.email }}</p>
            {% if current_user.is_admin %}

                <button onclick="showUsers()" style="display: inline-block; color: white; text-decoration: none; padding: .5em 2em; outline: none; border-width: 2px 0; border-style: solid none; border-color: #B0E0E6; font-weight: bold; text-align: center; border-radius: 6px; background: linear-gradient(#5F9EA0, #7B68EE) #B0E0E6; transition: 0.2s;">All Users</button>
                <ul id="users-list" style="display: none;">
                    {% for user in users %}
                        <li>
                            <div class="myuser">
                                <img src="{{ url_for('static', filename='users/' + user.username  + '/avatars/' + user.img_file ) }}" alt=""
                                     class="mr-3 mt-3 rounded-circle" style="width: 30px; border-radius: 15px;">
                            </div>
                            <a href="{{ url_for('task.show_tasks', username=user.username) }}" style="width: 130px; height: 40px; color: #fff; border-radius: 15px; padding: 10px 25px; font-family: 'Lato', sans-serif; font-weight: 500; background: transparent; cursor: pointer; transition: all 0.3s ease; position: relative; display: inline-block; box-shadow: inset 2px 2px 2px 0px rgba(255,255,255,.5), 7px 7px 20px 0px rgba(0,0,0,.1), 4px 4px 5px 0px rgba(0,0,0,.1); outline: none;">
                                <span style="position: relative; display: block; width: 100%; height: 100%;">
                                {{ user.username }}
                                </span>
                            </a>

                            <h6 style="display: inline-block; background-color: #8B0000; color: black; border-radius: 15px; padding: 10px 20px; text-decoration: none; font-weight: bold;"><a href="{{ url_for('main.delete_user', username=user.username) }}"> Delete {{  user.username }}</a></h6>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% else %}
            <p>Please log in to access your account.</p>
        {% endif %}
    </div>
    <div class="modal" id="avatar-modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <form method="POST" action="{{ url_for('main.account') }}" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.username.label }} {{ form.username }}
                </div>
                <div class="form-group">
                    {{ form.email.label }} {{ form.email }}
                </div>
                <div class="form-group" style="background-color: #20B2AA; color: #fff; border-radius: 20px;
                padding: 5px 18px; display: inline-block; cursor: pointer;">
                    <label for="avatar">Avatar</label>
                    <input type="file" name="avatar" id="avatar" class="avatar-input">
                </div>
                <div class="form-group">
                    <button type="submit" class="rounded-button">Submit</button>
                </div>
            </form>
        </div>
    </div>

    <script>
        var avatarImg = document.getElementById("avatar-img");
        var modal = document.getElementById("avatar-modal");
        var span = document.getElementsByClassName("close")[0];
        var usersList = document.getElementById("users-list");

        avatarImg.onclick = function() {
            modal.style.display = "block";
        };

        span.onclick = function() {
            modal.style.display = "none";
        };

        window.onclick = function(event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        };

        function showUsers() {
            if (usersList.style.display === "none") {
                usersList.style.display = "block";
            } else {
                usersList.style.display = "none";
            }
        }
    </script>
{% endblock content %}

{% block footer %}
    <footer class="footer">Task-Manager made by Simon Golovinskiy<br></footer>
{% endblock footer %}

task_manage/templates/add_task.html
{% extends 'base.html' %}

{% block content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='/styles/task_create.css') }}">
    <div class="sea-theme-heading">
        <h2>Create a New Task</h2>
    </div>
    <div class="avatar">
        <img id="avatar-img" src="{{ url_for('static', filename='users/' + current_user.username + '/avatars/' + current_user.img_file) }}" alt="">
    </div>
    <form class="sea-theme-form" method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.title.label }} {{ form.title(class='form-control') }}
        </div>
        <div class="form-group">
            {{ form.contain.label }} {{ form.contain(class='form-control') }}
        </div>
        <div class="form-group">
            {{ form.report.label }} {{ form.report(class='form-control-file') }}
        </div>
        {% if current_user.is_admin %}
            <div class="form-group">
                {{ form.user.label }} {{ form.user(class='form-control') }}
            </div>
        {% endif %}
        <div class="form-group">
            {{ form.submit(class='btn btn-primary') }}
        </div>
    </form>
{% endblock %}

task_manage/templates/admin.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Admin Panel</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='/styles/admin.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
    <style>
        body {
            background-color: #f8f9fa;
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 40px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
            margin-bottom: 30px;
        }

        h2 {
            margin-top: 40px;
            margin-bottom: 20px;
        }

        .form-container {
            margin-bottom: 20px;
        }

        .btn-assign {
            margin-top: 10px;
        }

        .user-list {
            list-style-type: none;
            padding: 0;
            margin: 0;
        }

        .user-list li {
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Admin Panel</h1>

        <h2>Assign Admin</h2>
        <div class="form-container">
            {% if current_user.is_authenticated %}
            {% for user in users %}
            {% if not user.is_admin %}
            <form method="POST" action="{{ url_for('main.assign_admin', user_id=user.id) }}">
                <button type="submit" class="btn btn-primary btn-assign">Assign {{ user.username }} as Admin</button>
            </form>
            {% endif %}

            {% endfor %}
            {% endif %}
        </div>

        <h2>All Users</h2>
        <ul class="user-list">
            {% for user in users %}
            {% if not user.is_admin %}
                <li>{{ user.username }}</li>
            {% endif %}

            {% endfor %}
        </ul>
    </div>
</body>
</html>

task_manage/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='/styles/style.css') }}">

    {% block title %}
        {% if title %}
            <title>{{title}}</title>
        {% else %}
            <title>Task-manager</title>
        {% endif %}
    {% endblock title %}

</head>
<body>
    <div class="wrapper">
        {% block menu %}
            <header class="header">
                <div class="logo">
                    <img src="{{ url_for('static', filename='img/logo.png') }}" alt="logo">
                </div>
                <ul class="Main_menu">
                    <li><a href="{{ url_for('main.index') }}"><p>Main page</p></a></li>
                    {% if current_user.is_authenticated %}
                        <li><a href="/tasks"><p>Tasks</p></a></li>
                        <li><a href="{{url_for('task.add_task')}}"><p>Add task</p></a></li>
                        <li><a href="/account"><p>Account</p></a></li>
                        <li><a href="{{ url_for('main.logout') }}"><p>Logout</p></a></li>
                    {% else %}
                        <li><a href="{{ url_for('main.register') }}"><p>Registration</p></a></li>
                        <li><a href="{{ url_for('main.login') }}"><p>Login</p></a></li>
                    {% endif %}
                    <li><a href="{{ url_for('main.index') }}"><p>Home</p></a></li>
                </ul>
            </header>
        {% endblock menu %}

        {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        {% block content %}
            {% block registration_form %}
                <div class="registration_form">
                    <form action="{{ url_for('main.register') }}" method="POST">

                    </form>
                </div>
            {% endblock registration_form %}

            {% block login_form %}
                <div class="login_form">
                    <form action="{{ url_for('main.login') }}" method="POST">

                    </form>
                </div>
            {% endblock login_form %}
        {% endblock content %}

        {% block main_page %}
            <div class="content" style="font-size: 20px; color: #00BFFF; font-weight:bold; text-align: center;">
                This is a Task-manager, inspired by JIRA 2.0
            </div>
        {% endblock main_page %}

        {% block footer %}
            <footer class="footer" style="font-size: 20px; color: #FFD700; font-weight:bold; text-align: center;">Task-Manager made by Simon Golovinskiy<br>
            </footer>
        {% endblock footer %}
    </div>
</body>
</html>

task_manage/templates/index.html
{% extends 'base.html' %}

{% block main_page %}
    <div class="wrapper">


            <div class="description">
                <p class="names"> Task Manager Main page </p>



   </div>
</div>
{% endblock main_page %}

task_manage/templates/login.html
{% extends 'base.html' %}

{% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename='/styles/loginstyle.css') }}">

<div class="login_form">
    <form action="" method="POST">

        {{ form.hidden_tag() }}
        <legend class="legend">Login</legend>

        {% if form.username.errors %}
        {{ form.username(class='form-post-title is-invalid', placeholder='Username') }}
        <div class="invalid-feedback">
            {% for error in form.username.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.username(class='form-post-title', placeholder='Username') }}
        {% endif %}

        {% if form.password.errors %}
        {{ form.password(class='form-post-title is-invalid', placeholder='Password') }}
        <div class="invalid-feedback">
            {% for error in form.password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.password(class='form-post-title', placeholder='Password') }}
        {% endif %}

        <div class="form-group_button">
            {{ form.submit(class='btn_sign_in', value='Sign In') }}
            {% if current_user.is_authenticated %}
            <small class="text-muted">
                Already logged in. Go to <a class='ml-2' href="{{ url_for('main.index') }}">Main Page</a>.
            </small>
            {% else %}
            <small class="text-muted">
                Don't have an account? <a class='ml-2' href="{{ url_for('main.register') }}">Register</a>
                or <a class='ml-2' href="{{ url_for('main.reset_request') }}">Forgot Password?</a>
            </small>
            {% endif %}
        </div>

    </form>
</div>

{% endblock content %}

task_manage/templates/register.html
{% extends 'base.html' %}

{% block content %}

<link rel="stylesheet" href="{{ url_for('static', filename='/styles/registerstyle.css') }}">

<div class="register_form">
    <form action="" method="POST">

        {{ form.hidden_tag() }}

        {% if form.username.errors %}
        {{ form.username(class='form-post-title is-invalid', placeholder='Username') }}
        <div class="invalid-feedback">
            {% for error in form.username.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.username(class='form-post-title', placeholder='Username') }}
        {% endif %}

        {% if form.email.errors %}
        {{ form.email(class='form-post-title is-invalid', placeholder='E-mail') }}
        <div class="invalid-feedback">
            {% for error in form.email.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.email(class='form-post-title', placeholder='E-mail') }}
        {% endif %}

        {% if form.password.errors %}
        {{ form.password(class='form-post-title is-invalid', placeholder='Password') }}
        <div class="invalid-feedback">
            {% for error in form.password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.password(class='form-post-title', placeholder='Password') }}
        {% endif %}

        {% if form.confirm_password.errors %}
        {{ form.confirm_password(class='form-post-title is-invalid', placeholder='Confirm Password') }}
        <div class="invalid-feedback">
            {% for error in form.confirm_password.errors %}
            <span>{{ error }}</span>
            {% endfor %}
        </div>
        {% else %}
        {{ form.confirm_password(class='form-post-title', placeholder='Confirm Password') }}
        {% endif %}

        <div class="form-group_button">
            {{ form.submit(class='btn_sign_in', value='Register') }}
            <small class="text-muted">
                Already have an account? <a class='ml-2' href="{{ url_for('main.login') }}">Login</a>
            </small>
        </div>

    </form>
</div>

{% endblock content %}

task_manage/templates/reset_request.html
{% extends 'base.html' %}

{% block content %}
  <link rel="stylesheet" href="{{ url_for('static', filename='/styles/reset_request.css') }}">
  <h1>Password Reset</h1>
  <p style="font-weight: bold; text-align:center;">Please enter your email address to receive instructions on how to reset your password.</p>

  <form method="POST" style="text-align:center;">
    {{ form.hidden_tag() }}

    <div class="form-group reset-password">
      {{ form.email.label(class_='form-label') }}
      {{ form.email(class_='form-control') }}
    </div>

    <button type="submit" class="btn btn-primary">Reset Password</button>
  </form>
{% endblock %}

task_manage/templates/reset_token.html
{% extends 'base.html' %}

{% block content %}
  <h1>Password Reset</h1>
  <p style="color: green; text-align: center; font-weight: bold;">Please enter a new password for your account.</p>

  <style>
    form {
      margin: 20px auto;
      max-width: 400px;
      padding: 20px;
      border: 1px solid #ccc;
      border-radius: 4px;
      background-color: #f5f5f5;
    }

    h1 {
      margin-top: 0;
    }

    .form-group {
      margin-bottom: 15px;
    }

    .form-label {
      font-weight: bold;
    }

    .form-control {
      width: 100%;
      padding: 8px;
      font-size: 16px;
      border-radius: 4px;
      border: 1px solid #ccc;
    }

    .btn-primary {
      background-color: #007bff;
      color: #fff;
      border: none;
      padding: 10px 20px;
      font-size: 16px;
      border-radius: 4px;
      cursor: pointer;
    }

    .btn-primary:hover {
      background-color: #0056b3;
    }

    .btn-primary:focus {
      outline: none;
    }
  </style>

  <form method="POST">
    {{ form.hidden_tag() }}

    <div class="form-group">
      {{ form.password.label(class_='form-label') }}
      {{ form.password(class_='form-control') }}
    </div>

    <div class="form-group">
      {{ form.confirm_password.label(class_='form-label') }}
      {{ form.confirm_password(class_='form-control') }}
    </div>

    <button type="submit" class="btn btn-primary">Reset Password</button>
  </form>
{% endblock %}

task_manage/templates/show_tasks.html
{% extends 'base.html' %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='styles/showing_task.css') }}">
{% if current_user.id == 1 %}
<h1>You are admin, check the Tasks </h1>
{% else %}
<h1>{{ current_user.username }}'s Tasks</h1>
{% endif %}

{% if tasks.items|length %}
  {% for task in tasks.items %}
    <div class="task" style="background: linear-gradient(-20deg, #616161 0%, #9bc5c3 100%);">
      <h2>{{ task.title }}</h2>

      <p>{{ task.task_date.strftime('%Y-%m-%d %H:%M') }}</p>
      <p>Report File:
        <a class="report-file-link" href="{{ url_for('task.download_file', task_id=task.id, filename=task.report) }}" style="background: linear-gradient(-20deg, #616161 0%, #9bc5c3 100%); border: 2px solid black; font-size: 14px; padding: 5px 20px; border-radius: 15px;">Download report</a>
      </p>
      {% if task.updated %}
        <p style="color: #00FF00">Ready for submit <span class="updated-mark">&#10004;</span></p>
      {% endif %}
      <button class="details-btn" style="background-color: #20B2AA; color: #fff; border-radius: 20px; padding: 5px 18px; display: inline-block; cursor: pointer;">Details</button>
      <a href="{{ url_for('task.task_commit', task_id=task.id) }}" class="commit-btn" style="background-color: #20B2AA; color: #fff; border-radius: 20px; padding: 5px 18px; display: inline-block; cursor: pointer;">Commit</a>
      {% if current_user.is_admin or current_user.id == task.user_id %}
      <form class="delete-form" action="{{ url_for('task.task_delete', task_id=task.id) }}" method="POST" style="display: inline-block;">
        <button type="submit" class="delete-btn" style="background-color: #FF4500; color: #fff; border-radius: 20px; padding: 5px 18px; display: inline-block; cursor: pointer;">Delete</button>
      </form>
      {% endif %}
      <div class="modal">
        <div class="modal-content">
          <h2>{{ task.contain }}</h2>
          <p>{{ task.details }}</p>
          <button class="close-btn">Close</button>
        </div>
      </div>
    </div>
  {% endfor %}
{% else %}
  <p class="no-tasks">No tasks for now, {{ current_user.username }} =)</p>
{% endif %}

<div class="pagination">
  {% if tasks.has_prev %}
    <a href="{{ url_for('task.show_tasks', page=tasks.prev_num) }}" class="second_button">Previous</a>
  {% endif %}
  {% if tasks.has_next %}
    <a href="{{ url_for('task.show_tasks', page=tasks.next_num) }}" class="second_button">Next</a>
  {% endif %}
</div>

<script>
  var detailsButtons = document.querySelectorAll('.details-btn');
  var modalCloseButtons = document.querySelectorAll('.close-btn');
  var modals = document.querySelectorAll('.modal');

  detailsButtons.forEach(function(button, index) {
    button.addEventListener('click', function() {
      modals[index].style.display = 'block';
    });
  });

  modalCloseButtons.forEach(function(button, index) {
    button.addEventListener('click', function() {
      modals[index].style.display = 'none';
    });
  });
</script>

{% endblock %}

task_manage/templates/task_commit.html
{% extends 'base.html' %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='styles/task_commit.css') }}">

<h1>Commit Task</h1>

<div class="task">
  <h2>{{ task.title }}</h2>
  <p>{{ task.task_date }}</p>

  <form method="POST" action="{{ url_for('task.task_commit', task_id=task.id) }}" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.title.label(class="form-control-label") }}
      {{ form.title(class="form-control") }}
    </div>
    <div class="form-group">
      {{ form.report.label(class="form-control-label") }}
      {{ form.report(class="form-control-file") }}
    </div>
    <div class="form-group">
      {{ form.contain.label(class="form-control-label") }}
      {{ form.contain(class="form-control") }}
    </div>
    <button type="submit" class="btn btn-primary">Commit</button>
  </form>
</div>

{% endblock %}